/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#faf9f5",
        "background-dark": "#262624",
        foreground: "#3d3929",
        "foreground-dark": "#c3c0b6",
        card: "#eff6ff",
        "card-dark": "#262624",
        "card-foreground": "#141413",
        "card-foreground-dark": "#faf9f5",
        popover: "#faf9f5",
        "popover-dark": "#30302e",
        "popover-foreground": "#28261b",
        "popover-foreground-dark": "#e5e5e2",
        primary: "#bce4f8",
        "primary-dark": "#4194d7",
        "primary-foreground": "#000000",
        "primary-foreground-dark": "#ffffff",
        secondary: "#bce4f8",
        "secondary-dark": "#faf9f5",
        "secondary-foreground": "#000000",
        "secondary-foreground-dark": "#30302e",
        muted: "#ede9de",
        "muted-dark": "#1b1b19",
        "muted-foreground": "#83827d",
        "muted-foreground-dark": "#b7b5a9",
        accent: "#bce4f8",
        "accent-dark": "#1a1915",
        "accent-foreground": "#28261b",
        "accent-foreground-dark": "#f5f4ee",
        destructive: "#141413",
        "destructive-dark": "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#dad9d4",
        "border-dark": "#3e3e38",
        input: "#bce4f8",
        "input-dark": "#52514a",
        ring: "#4194d7",
        "chart-1": "#9e1c47",
        "chart-1-dark": "#b05730",
        "chart-2": "#99999c",
        "chart-2-dark": "#9c87f5",
        "chart-3": "#013761",
        "chart-3-dark": "#1a1915",
        "chart-4": "#bce4f8",
        "chart-4-dark": "#2f2b48",
        "chart-5": "#fbbf17",
        "chart-5-dark": "#b4552d",
        sidebar: "#f5f4ee",
        "sidebar-dark": "#1f1e1d",
        "sidebar-foreground": "#3d3d3a",
        "sidebar-foreground-dark": "#c3c0b6",
        "sidebar-primary": "#c96442",
        "sidebar-primary-dark": "#343434",
        "sidebar-primary-foreground": "#fbfbfb",
        "sidebar-accent": "#e9e6dc",
        "sidebar-accent-dark": "#0f0f0e",
        "sidebar-accent-foreground": "#343434",
        "sidebar-accent-foreground-dark": "#c3c0b6",
        "sidebar-border": "#ebebeb",
        "sidebar-ring": "#b5b5b5",
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
    },
  },
  plugins: [],
};
