// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingStatus string

const (
	BookingStatusCreated   BookingStatus = "created"
	BookingStatusReceived  BookingStatus = "received"
	BookingStatusWashing   BookingStatus = "washing"
	BookingStatusReady     BookingStatus = "ready"
	BookingStatusCollected BookingStatus = "collected"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type UserRole string

const (
	UserRoleStudent UserRole = "student"
	UserRoleStaff   UserRole = "staff"
	UserRoleWarden  UserRole = "warden"
	UserRoleAdmin   UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Bag struct {
	ID        pgtype.UUID      `json:"id"`
	StudentID pgtype.UUID      `json:"student_id"`
	QrCode    string           `json:"qr_code"`
	IsActive  pgtype.Bool      `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Block struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Booking struct {
	ID               pgtype.UUID      `json:"id"`
	StudentID        pgtype.UUID      `json:"student_id"`
	BagID            pgtype.UUID      `json:"bag_id"`
	Status           BookingStatus    `json:"status"`
	DropTime         pgtype.Timestamp `json:"drop_time"`
	WashCompleteTime pgtype.Timestamp `json:"wash_complete_time"`
	PickupTime       pgtype.Timestamp `json:"pickup_time"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type Floor struct {
	ID          pgtype.UUID      `json:"id"`
	BlockID     pgtype.UUID      `json:"block_id"`
	FloorNumber int32            `json:"floor_number"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type LaundryService struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Phone     pgtype.Text      `json:"phone"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type LaundryStaff struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	Name             string           `json:"name"`
	Phone            pgtype.Text      `json:"phone"`
	LaundryServiceID pgtype.UUID      `json:"laundry_service_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type Room struct {
	ID         pgtype.UUID      `json:"id"`
	FloorID    pgtype.UUID      `json:"floor_id"`
	RoomNumber int32            `json:"room_number"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type ScheduleInstance struct {
	ID         pgtype.UUID      `json:"id"`
	TemplateID pgtype.UUID      `json:"template_id"`
	Month      pgtype.Int4      `json:"month"`
	Year       pgtype.Int4      `json:"year"`
	IsActive   pgtype.Bool      `json:"is_active"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type ScheduleTemplate struct {
	ID              pgtype.UUID      `json:"id"`
	BlockID         pgtype.UUID      `json:"block_id"`
	RoomStart       pgtype.Int4      `json:"room_start"`
	RoomEnd         pgtype.Int4      `json:"room_end"`
	DayOfWeek       pgtype.Int4      `json:"day_of_week"`
	DropStartTime   pgtype.Time      `json:"drop_start_time"`
	DropEndTime     pgtype.Time      `json:"drop_end_time"`
	PickupStartTime pgtype.Time      `json:"pickup_start_time"`
	PickupEndTime   pgtype.Time      `json:"pickup_end_time"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Student struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Name      string           `json:"name"`
	Phone     pgtype.Text      `json:"phone"`
	RoomID    pgtype.UUID      `json:"room_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      UserRole         `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Warden struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Name      string           `json:"name"`
	Phone     pgtype.Text      `json:"phone"`
	BlockID   pgtype.UUID      `json:"block_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
